[package]
name = "for_streams"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
futures = "0.3.31"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0.110", features = ["full"] }

[dev-dependencies]
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.17"
