[package]
name = "for-streams"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
for-streams-impl = { version = "0.1.0", path = "impl" }

[dev-dependencies]
rand = "0.9.2"
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.17"
